import Head from "next/head";
import { table, minifyRecords } from "./api/utils/Airtable-todo";
import Todo from "../components/Todo";
import Nav from "../components/Nav";
import React,{ useEffect, useState, useContext } from 'react';
import { TodosContext } from '../context/TodosContext';


export default function Home(initialTodos) {
  const { todos, setTodos } = useContext(TodosContext);
  useEffect(() => {
      setTodos(initialTodos.initialTodos);
  }, []);
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <table>
      <tr>
        <th>Name</th>
        <th>Difficulty</th>
        <th>Status</th>
      </tr>
      {todos && todos.map((todo) => {
        return(
        <Todo key={todo.id} todo={todo} />
        )
      })}


      </table>

    </div>
  );
}

export async function getServerSideProps(context) {
  try {
    const todos = await table.select({}).firstPage();
    return {
      props: {
        initialTodos: minifyRecords(todos),
      },
    };
  } catch (err) {
    console.error(err);
    return {
      props: {
        err: "Something went wrong",
      },
    };
  }
}
